on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/5fa7a9a1913258140495e42526dd1875
          gist_title: Pr치ctica-19 Serial 4550-MikroC.c
          gist_description: Pr치cticas MikroC Pro for PIC
          github_file: Proyecto/Bluethooth/4550/SERIAL.c
          file_encoding: WINDOWS-1252
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/33ed7ee3874243f945e7bccf8ef309e9
          gist_title: Pr치ctica-19 Serial 45K50-MikroC.c
          gist_description: Pr치cticas MikroC Pro for PIC
          github_file: Proyecto/Bluethooth/45K50/SERIAL.c
          file_encoding: WINDOWS-1252